### PR TITLE
Removing dead link

### PR DESCRIPTION
**Pull request by spekulatius**
just removing a dead link @stevesong

### CODE REVIEW

**Comment by stevesong** [comment]
Thanks!  Looking into it, that link appears to have moved here:  https://www.measurementlab.net/visualizations/

**Comment by spekulatius** [comment]
Oh, yeah @stevesong. I've re-added it with the updated link :+1:

**Review by stevesong — APPROVED** [review]

**Comment by stevesong** [comment]
Thanks Peter!

**Comment by spekulatius** [comment]
No worries, happy to help out Steve!

**Pull request merged**
